# commits can contain win, rhub or deploy text for specific actions
name: Check-other
on: push
jobs: 
  r-hub-checks:
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:latest
    if: "!contains(github.event.commits[0].message, '[skip other]')"
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v2

      - name: Initialize r-hub
        shell: Rscript {0}
        run: |
          install.packages("rhub")
          rhub::validate_email(
            email = "dawid.kaledkowski@gmail.com",
            token = "${{secrets.RHUB_TOKEN}}"
          )
      - name: Check rhub/debian-clang-devel
        run: Rscript --vanilla inst/automation-checks/check-rhub.R "debian-clang-devel"

      - name: Check r-hub/debian-gcc-devel
        run: Rscript --vanilla inst/automation-checks/check-rhub.R "debian-gcc-devel"

      - name: Check r-hub/linux-x86_64-rocker-gcc-san
        run: Rscript --vanilla inst/automation-checks/check-rhub.R "linux-x86_64-rocker-gcc-san"

      - name: Check r-hub/solaris-x86-patched
        run: Rscript --vanilla inst/automation-checks/check-rhub.R "solaris-x86-patched"

      - name: Check r-hub/fedora-clang-devel
        run: Rscript --vanilla inst/automation-checks/check-rhub.R "fedora-clang-devel"

  win-builder-checks:
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:latest
    if: "!contains(github.event.commits[0].message, '[skip other]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send package to win-builder
        shell: Rscript {0}
        run: |
          if (!require("devtools")) install.packages('devtools', repos = 'http://cran.rstudio.com')
          devtools::check_win_devel()
          devtools::check_win_oldrelease()
          devtools::check_win_release()
